project_id = "capacita-pro"

[functions.generate-course]
verify_jwt = true

[functions.import-workers]
verify_jwt = true

[functions.scrape-url]
enabled = true
verify_jwt = false
import_map = "./functions/scrape-url/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/scrape-url/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/scrape-url/*.html" ]
